package ddklient

const val DDK_CACHE_DIR_KEY = "DDK_CACHE_DIR"
const val DDK_KIND_KEY = "DDK_KIND"
const val DDK_DOMAIN_KEY = "DDK_DOMAIN"
const val DDK_PASSWORD_KEY = "DDK_PASSWORD"
const val DDK_HOSTS_KEY = "DDK_HOSTS"
const val DDK_TIMEOUT_SECONDS_KEY = "DDK_TIMEOUT_SECONDS"
